vultisig/vultisig-windows

frontend/src/App.tsx
frontend/src/components/vaultList/VaultList.tsx
frontend/src/pages/importVault/ImportVaultView.tsx
frontend/src/pages/onboarding/OnboardingView.tsx
frontend/src/pages/vaultList/VaultView.tsx
storage/migrate/000001_initial.up.sql
storage/store.go

This PR imports and shows the Vault list. 
It also auto-selects the first vault if there is only one.
It changes the title of the vault list when selected per the selected one.
I also fixed the database;
It also creates indexes for the queries.
https://github.com/vultisig/vultisig-windows/issues/49

Import and show the vault list

---

frontend/package.json.md5
frontend/wailsjs/go/models.ts
frontend/wailsjs/go/storage/Store.d.ts
frontend/wailsjs/go/storage/Store.js
storage/address_book.go
storage/migrate/000001_initial.down.sql
storage/migrate/000001_initial.up.sql
storage/settings.go
storage/store.go

This is the backend of settings. It includes:
Settings table
Save method
Get method
Struct/model
Address book table
Save method
Get method
Struct/model

Settingsdb

---

frontend/src/components/sendCrypto/SendCryptoForm.tsx
frontend/src/pages/send/SendCryptoView.tsx
frontend/src/pages/send/SendCryptoViewModel.tsx
frontend/src/pages/vault/VaultBalances.tsx
frontend/src/pages/vault/VaultItemView.tsx

Adds prices, balances, logos, to vault item and sending, also adds the max button and percentages

Price + balance + logo + Max 100%, 50%, 25%

---

frontend/package-lock.json
frontend/src/pages/send/SendCryptoViewModel.tsx
frontend/src/services/Fee/utxo/FeeServiceUtxo.ts
frontend/src/vault/components/sendDeprecated/SendCoinPromptDeprecated.tsx

https://blockchair.com/dogecoin/transaction/c179cad42ade0b65e1d365ea65eb3b23f10a712c2078566e2a2b65a7fad94eb2

Tests for sending UTXO

---

.eslintrc.json
frontend/src/model/evm-fee-mode.ts
frontend/src/model/gas-info.ts
frontend/src/services/Blockchain/BlockchainService.ts
frontend/src/services/Blockchain/BlockchainServiceFactory.ts
frontend/src/services/Blockchain/IBlockchainService.ts
frontend/src/services/Blockchain/evm/BlockchainServiceEvm.ts
frontend/src/services/Rpc/IRpcService.ts
frontend/src/services/Rpc/evm/RpcServiceEvm.ts
frontend/src/vault/components/sendDeprecated/SendCoinPromptDeprecated.tsx

We are now able to broadcast transactions for native tokens on EVM
Ethereum
https://etherscan.io/address/0x4bf231bf4cb92e8d249a3d8db813f075ba1c5dfe
https://etherscan.io/tx/0x022a6cf7daadb6a3c78934145cefbdc16a5018eee0d03aa28b019f07de0e4808
Base
https://basescan.org/tx/0x0e6845a1ab211450a22031da68d4407945c182f7dded3f455a231101d5f9950d

EVM end to end

---

frontend/src/App.tsx
frontend/src/router.tsx

fix: routing system

---

frontend/src/services/Blockchain/evm/BlockchainServiceEvm.ts
frontend/src/services/Send/evm/SendServiceEvm.ts
frontend/src/vault/components/sendDeprecated/SendCoinPromptDeprecated.tsx

**Tests:**
**ERC 20 broadcast**
https://etherscan.io/tx/0x7181fd7430fe24c100c3e332b2b871f5c891bc46dd434d9cded1854f8f3d4c83
**ETH**
https://etherscan.io/tx/0x8bb50c6bf949c67749356ceca9efb98f4d174cefc9716dce50e233900d1f8f44

erc20 end to end

---

frontend/src/i18n/locales/en/translation.json
frontend/src/navigation/index.ts
frontend/src/pages/vaultSettings/vaulFaq/FaqVaultPage.styles.tsx
frontend/src/pages/vaultSettings/vaulFaq/FaqVaultPage.tsx
frontend/src/pages/vaultSettings/vaulFaq/constants.ts
frontend/src/router.tsx

feat: faq page UI and content

---

frontend/package-lock.json
frontend/package.json
frontend/src/lib/ui/icons/CaretDownIcon.tsx
frontend/src/lib/ui/icons/CaretUpIcon.tsx
frontend/src/pages/vaultSettings/vaulFaq/FaqVaultPage.styles.tsx
frontend/src/pages/vaultSettings/vaulFaq/FaqVaultPage.tsx

Complete FAQ page + Smooth animations using framer motion on the FAQ when expanding content

feat: layout and animations

---

frontend/src/pages/vaultSettings/vaultDefaultChains/VaultDefaultChains.tsx
frontend/src/vault/mutations/useUpdateVaultSettings.ts
go.mod
go.sum
storage/store.go

Implement logic for default chains

feat: implement default chains logic

---

.gitignore
.vscode/launch.json
.vscode/tasks.json
go.mod
go.sum
storage/migrate/000001_initial.up.sql
storage/store.go

https://github.com/vultisig/vultisig-windows/issues/321

settings fixes

---

frontend/src/i18n/locales/en/translation.json
frontend/src/lib/utils/formatAmount.ts
frontend/src/lib/utils/record/omit.ts
frontend/src/navigation/hooks/useAppPathParams.ts
frontend/src/vault/keygen/shared/KeygenPendingState.tsx
frontend/src/vault/keygen/shared/KeygenProgressIndicator.tsx
frontend/src/vault/keygen/shared/MatchKeygenSessionStatus.tsx
frontend/src/vault/keysign/shared/KeysignSigningState.tsx
frontend/src/vault/keysign/shared/KeysignSigningStep.tsx
frontend/src/vault/keysign/shared/KeysignSummaryStep.tsx
frontend/src/vault/keysign/shared/state/currentPeers.tsx
frontend/src/vault/keysign/shared/state/selectedPeers.tsx
frontend/src/vault/keysign/start/StartKeysignPage.tsx
frontend/src/vault/keysign/start/peerDiscovery/KeysignPeerDiscovery.tsx
frontend/src/vault/send/fee/SendNetworkFeeValue.tsx
frontend/src/vault/send/memo/ManageMemo.tsx
frontend/src/vault/send/receiver/ManageReceiver.tsx
frontend/src/vault/setup/SetupVaultPage.tsx
frontend/src/vault/setup/hooks/useVaultKegenDevices.ts
frontend/src/vault/setup/peerDiscovery/CurrentPeersCorrector.tsx
frontend/src/vault/setup/peerDiscovery/hooks/useIsPeerDiscoveryStepDisabled.ts
frontend/src/vault/setup/peerDiscovery/peers/PeerOption.tsx

* Fix fee formatting.
* Implement a collapsible memo.
* Fix the back button behavior after changing the selected coin for sending.
* Correct price formatting.
* Select the device by default during pairing.
* Continue the keysigning process automatically after the necessary devices have joined.
* Fix the keysigning progress message.
* Update the keysigning final screen.

Send Form improvements

---

main.go
wails.json

Update name from Vultisig-win -> Vultisig

---

frontend/src/vault/keygen/shared/peerDiscovery/KeygenPeerDiscovery.tsx
frontend/src/vault/keygen/shared/peerDiscovery/KeygenPeerDiscoveryQrCode.tsx

fix QR code sizing for keygen flow

fix: QR code

---

frontend/src/components/dialog/ImportVaultDialog.tsx
frontend/src/pages/edItVault/vaultDeleteSettings/DeleteVaultPage.tsx
frontend/src/pages/importVault/ImportVaultView.tsx
frontend/src/services/Coin/DefaultCoinsService.ts

1. Fix Import passwod dialog to show cancen button
2. After delete vault , navigate user to vault list screen
3. Import vault to support .vult
4. DefaultCoinService only add coins which "isNativeToken" is true

A few bug fixes

---

frontend/src/chain/components/address/AddressPage.tsx
frontend/src/lib/ui/qr/FramedQrCode.tsx
frontend/src/ui/qr/PrintableQrCode.tsx
frontend/src/vault/chain/VaultChainPage.tsx
frontend/src/vault/keygen/shared/peerDiscovery/KeygenPeerDiscoveryQrCode.tsx
frontend/src/vault/keysign/start/peerDiscovery/KeysignPeerDiscoveryCode.tsx

Fix QR codes around the app, fixes this: https://github.com/vultisig/vultisig-windows/issues/399

fix: all QR codes around the app

---

frontend/src/services/Vault/VaultService.ts

vault backup standard, solves: https://github.com/vultisig/vultisig-windows/issues/361

feat: adjust vault backup naming and file extension

---

frontend/src/services/Blockchain/ton/BlockchainServiceTon.ts

bounce back tx
https://tonscan.org/tx/854ab4123eb3b188d70fa1ac8c215d2d0badf68195f33115b31528ffa52fd8e2

set to bounce back always

---

frontend/src/coin/utils/coinMeta.ts
frontend/src/i18n/locales/de/translation.json
frontend/src/i18n/locales/en/translation.json
frontend/src/i18n/locales/es/translation.json
frontend/src/i18n/locales/hr/translation.json
frontend/src/vault/chain/manage/coin/ManageVaultChainCoinsPrompt.tsx
frontend/src/vault/chain/manage/coin/VaultChainCoinOptions.tsx

fix: crashing when searching additional chain tokens on various chains, as per: https://github.com/vultisig/vultisig-windows/issues/421

fix: crashing when searching additional chain tokens

---

frontend/src/pages/vaultSettings/vaultDefaultChains/VaultDefaultChains.styles.tsx
frontend/src/pages/vaultSettings/vaultDefaultChains/VaultDefaultChains.tsx
frontend/src/services/Coin/DefaultCoinsService.ts

fixes: https://github.com/vultisig/vultisig-windows/issues/397

fix: default chains sortin, feat: sticky header

---

frontend/src/vault/send/form/hooks/useIsSendFormDisabled.tsx

Allow sender and receiver to be the same address
Fixes: https://github.com/vultisig/vultisig-windows/issues/356

fix: remove requirement for sender and receiver to be different

---

frontend/src/pages/edItVault/constants.ts
frontend/src/pages/edItVault/vaultDeleteSettings/DeleteVaultPage.tsx
package-lock.json

fixes: https://github.com/vultisig/vultisig-windows/issues/467

fix: wrong redirect after vault is deleted

---

frontend/src/chain/utils/getBlockExplorerUrl.ts

fixes: https://github.com/vultisig/vultisig-windows/issues/299

fix: thorchain transactions to use throchain explorer

---

frontend/src/chain/tx/components/TxOverviewRow.tsx
frontend/src/i18n/locales/de.ts
frontend/src/i18n/locales/en.ts
frontend/src/i18n/locales/es.ts
frontend/src/i18n/locales/hr.ts
frontend/src/i18n/locales/it.ts
frontend/src/i18n/locales/pt.ts
frontend/src/navigation/hooks/useAppPathParams.ts
frontend/src/navigation/index.ts
frontend/src/vault/deposit/DepositConfirmButton/index.tsx
frontend/src/vault/deposit/DepositForm/chainOptionsConfig.ts
frontend/src/vault/deposit/DepositForm/index.tsx
frontend/src/vault/deposit/DepositPage.tsx
frontend/src/vault/deposit/DepositVerify/index.tsx
frontend/src/vault/deposit/fee/DepositFee.tsx
frontend/src/vault/deposit/fee/DepositFeeValue.tsx
frontend/src/vault/deposit/fee/DepositFiatFee.tsx
frontend/src/vault/deposit/fee/DepositFiatFeeValue.tsx
frontend/src/vault/deposit/fee/DepositSpecificTxInfoProvider.tsx
frontend/src/vault/deposit/fee/StrictFeeRow.tsx
frontend/src/vault/deposit/hooks/useCurrentDepositCoin.ts
frontend/src/vault/deposit/hooks/useMemoGenerator.ts
frontend/src/vault/deposit/hooks/useSender.tsx
frontend/src/vault/deposit/queries/useSpecificDepositTxInfoQuery.ts
frontend/src/vault/deposit/utils/schema.ts
frontend/src/vault/deposit/utils/validateNodeAddress.ts
frontend/wailsjs/go/models.ts

feat: thorchain deposits fixes

---

frontend/src/pages/edItVault/vaultDetailsSettings/VaultDetailsPage.tsx

fixes: https://github.com/vultisig/vultisig-windows/issues/504

fix; vault details screen

---

frontend/src/vault/keygen/shared/KeygenBackup.tsx

fixes: https://github.com/vultisig/vultisig-windows/issues/502

fix: keygen backup page UI

---

frontend/src/lib/utils/formatAmount.ts
frontend/src/model/transaction.ts
frontend/src/vault/deposit/DepositConfirmButton/index.tsx
frontend/src/vault/deposit/DepositForm/chainOptionsConfig.ts

THORchain deposits polishing 1st iteration

fix: THORchain deposit polishes

---

frontend/src/i18n/locales/de.ts
frontend/src/i18n/locales/en.ts
frontend/src/i18n/locales/es.ts
frontend/src/i18n/locales/hr.ts
frontend/src/i18n/locales/it.ts
frontend/src/i18n/locales/pt.ts
frontend/src/model/transaction.ts
frontend/src/services/Blockchain/IBlockchainService.ts
frontend/src/vault/chain/VaultChainPage.tsx
frontend/src/vault/components/VaultPrimaryActions/config.ts
frontend/src/vault/components/VaultPrimaryActions/index.tsx
frontend/src/vault/deposit/DepositConfirmButton/config.ts
frontend/src/vault/deposit/DepositConfirmButton/index.tsx
frontend/src/vault/deposit/DepositConfirmButton/utils.ts
frontend/src/vault/deposit/DepositForm/chainOptionsConfig.ts
frontend/src/vault/deposit/DepositForm/index.tsx
frontend/src/vault/deposit/DepositPage.tsx
frontend/src/vault/deposit/DepositVerify/index.tsx
frontend/src/vault/deposit/hooks/useGetAmountTotalBalance.ts
frontend/src/vault/deposit/hooks/useMemoGenerator.ts
frontend/src/vault/deposit/utils/schema.ts
frontend/src/vault/queries/useVaultChainCoinsQuery.ts

add support for all THORchain actions: bond, unbond, stake, vote, etc.

feat: add support for all thorchain actions

---

frontend/src/pages/importVault/ImportVaultView.tsx
frontend/src/pages/vaultSettings/vaultDefaultChains/VaultDefaultChains.tsx
frontend/src/services/Coin/DefaultCoinsService.ts
frontend/src/vault/keygen/shared/mutations/useKeygenMutation.ts
frontend/src/vault/mutations/useSaveVaultMutation.ts

fixes: https://github.com/vultisig/vultisig-windows/issues/484

fix: default chains not applying to new vautls

---

frontend/src/i18n/locales/es.ts
frontend/src/i18n/locales/it.ts
frontend/src/i18n/locales/pt.ts

fixes: https://github.com/vultisig/vultisig-windows/issues/481

fix: labels

---

frontend/src/i18n/locales/de.ts
frontend/src/i18n/locales/en.ts
frontend/src/i18n/locales/es.ts
frontend/src/i18n/locales/hr.ts
frontend/src/i18n/locales/it.ts
frontend/src/i18n/locales/pt.ts
frontend/src/vault/deposit/DepositForm/chainOptionsConfig.ts
frontend/src/vault/deposit/DepositForm/index.tsx

fixes: https://github.com/vultisig/vultisig-windows/issues/601

feat: extend thorchain deposit feature for all other supported chains

---

frontend/src/i18n/locales/de.ts
frontend/src/i18n/locales/en.ts
frontend/src/i18n/locales/es.ts
frontend/src/i18n/locales/hr.ts
frontend/src/i18n/locales/it.ts
frontend/src/i18n/locales/pt.ts
frontend/src/pages/edItVault/vaultDeleteSettings/DeleteVaultPage.tsx

fixes: https://github.com/vultisig/vultisig-windows/issues/518 + includes complete refactoring of the Delete Page introducing more readable code

feat: translations

---

frontend/src/coin/query/useSpecificTxInfoQuery.ts
frontend/src/services/Rpc/IRpcService.ts
frontend/src/services/Rpc/evm/RpcServiceEvm.ts
frontend/src/services/Rpc/evm/RpcServiceZkSyncEvm.ts
frontend/src/services/Rpc/solana/RpcServiceSolana.ts
frontend/src/services/Rpc/utxo/RpcServiceUtxo.ts
frontend/src/vault/deposit/queries/useSpecificDepositTxInfoQuery.ts

Txid: https://solscan.io/tx/2ktJ4fzTTpd7xnRoQ52mJY6yMJP3agKNMhHBWGNCYN8Tfdcg1TVRw5VYU9tQcjo2Nv8M5EhPmbat5jvMuVmyodDE
Destination: CVAPxRchnZnxnyTmzY7K6oVRvDnYSEo26CXnSB5wgL7
https://explorer.solana.com/address/CVAPxRchnZnxnyTmzY7K6oVRvDnYSEo26CXnSB5wgL7

spl issues

---

frontend/src/services/Blockchain/solana/BlockchainServiceSolana.ts
frontend/src/services/Rpc/solana/RpcServiceSolana.ts

https://omniatech.io/pages/solana-transaction-confirmation/
https://solscan.io/tx/2uLKhECS2yYxzF5oLtpYsGZeHqdQNFwNKr7xRnffPKpUEd8NXeeULru5CkJK8UW7z6ZEAG65uhnYXZpPRUhSx9P2
https://solscan.io/tx/4tb2p4HWDp4FbkhiDkbWvfYgss5UJzxDrc9x4JCNCoUL5ZezyateBBafjfopKTtk6e3TT6qCSF68pxoeFFHuBYQm

Spl confirmation

---

frontend/public/assets/icons/coins/maya.svg

fixes: https://github.com/vultisig/vultisig-windows/issues/668

feat: add maya icon

---

frontend/src/pages/edItVault/vaultDeleteSettings/DeleteVaultPage.tsx

fix: currency symbol

---

frontend/src/coin/utils/sortCoinsByBalance.ts

Add min threshold for token balances after auto discovery

feat: add min threshold for tokens balances

---

frontend/src/vault/deposit/utils/memoGenerator/index.ts

fix: TON function MEMO

---

app.go
frontend/src/i18n/locales/de.ts
frontend/src/i18n/locales/en.ts
frontend/src/i18n/locales/es.ts
frontend/src/i18n/locales/hr.ts
frontend/src/i18n/locales/it.ts
frontend/src/i18n/locales/pt.ts
frontend/src/services/Vault/VaultService.ts

Fix backup logic and improve locales
To fix: https://github.com/vultisig/vultisig-windows/issues/754 and https://github.com/vultisig/vultisig-windows/issues/753

Fix/backup logic and backup page UI

---

frontend/src/vault/deposit/DepositForm/index.tsx

Prevent scrolling using mouse wheel

fix: prevent changing value with mouse wheel

---

clients/extension/src/background/index.ts
clients/extension/src/content/index.ts
clients/extension/src/pages/transaction/index.tsx
clients/extension/src/types/thorchain.ts
clients/extension/src/utils/api.ts
clients/extension/src/utils/interfaces.ts

Superseeds https://github.com/vultisig/vulticonnect/pull/111

feat: improve extension typings

---

clients/extension/src/utils/constants.ts

Fix https://github.com/vultisig/vultisig-windows/issues/894

Update vulticonnect solana explorer

---

clients/extension/src/i18n/locales/en_UK.ts

Update scan text

---

clients/extension/manifest.config.js

Fix vulticonnect extention name

---

clients/extension/src/pages/transaction/index.scss

Fix QR code scale issue

---

clients/extension/src/types/thorchain.ts
clients/extension/src/utils/api.ts

Fixed Thorchain type

---

clients/extension/src/content/index.ts

Fix Vulticonnect injection

---

.github/workflows/build.yml

add test and extension build to ci

---

clients/desktop/src/vault/keygen/shared/mutations/useKeygenMutation.ts
clients/desktop/src/vault/server/components/WaitForServerStates.tsx
clients/desktop/src/vault/server/hooks/useWaitForServerAnimationStates.ts
clients/desktop/src/vault/setup/fast/SetupFastVaultCreationStep.tsx
clients/desktop/src/vault/setup/fast/SetupVaultServerStep.tsx
clients/desktop/src/vault/setup/fast/hooks/useCreateVaultSetup.ts

Fix: vault creation not working after Fast Vault flow
Fix: https://github.com/vultisig/vultisig-windows/issues/916

Fix: vault not saved after fast vault creation flow

---

clients/desktop/src/lib/ui/query/components/MatchQuery.tsx
clients/desktop/src/vault/server/components/WaitForServerStates.tsx
clients/desktop/src/vault/server/components/WaitForServerToJoinStep.tsx

fixes: https://github.com/vultisig/vultisig-windows/issues/916

fix: issue with keysign not being triggered

---

clients/desktop/src/chain/keysign/chainSpecific/getEthereumSpecific.ts

This should fix https://github.com/vultisig/vultisig-windows/issues/917
https://arbiscan.io/tx/0x09ad20e719462b10b490f6c3d8b78e1a6150186bf1fd9bc1db18cafd059c82e9

maxFeePerGasWei

---

lib/utils/formatAmount.ts

Fix to https://github.com/vultisig/vultisig-windows/issues/780

if token should be min 8 decimal places

---

clients/desktop/src/chain/evm/utils/getEvmBaseFee.ts
clients/desktop/src/chain/solana/client/getSolanaClient.ts

allow basefeePerGas to be 0

---

.gitignore
clients/desktop/src/coin/jupiter/token.ts
clients/desktop/src/coin/query/useWhitelistedCoinsQuery.ts

Jupiter white list tokens

---

clients/desktop/src/i18n/locales/de.ts
clients/desktop/src/i18n/locales/en.ts
clients/desktop/src/i18n/locales/es.ts
clients/desktop/src/i18n/locales/hr.ts
clients/desktop/src/i18n/locales/it.ts
clients/desktop/src/i18n/locales/pt.ts
clients/desktop/src/vault/setup/shared/SetupVaultSummaryStep/index.tsx
clients/desktop/src/vault/setup/shared/SetupVaultSummaryStepOld/index.tsx

fix: backup summary copy

---

core/ui/vault/settings/index.tsx

Please include a summary of the change and which issue is fixed. 
Fixes #1475

Hide reshare option for Fast Vault

---

ci/deb/nfpm.yaml
clients/desktop/build.json

Please include a summary of the change and which issue is fixed. 
Fixes #<issue-number>

Bump version to 1.0.38 in nfpm.yaml and build.json
